config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts

  root 'posts#index'
  get '/about', to: 'pages#about'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "400x500#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = current_admin.posts.build
  end

  def create
    @post = current_admin.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Ubuntu:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand"><%= link_to "MyBlog", root_path %></div>

      <% if admin_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Account", edit_admin_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Admin Login", new_admin_session_path %></li>
        </ul>
      <% end %>
      </div>
  </nav>

  <div class="container">
    <% flash.each do |name,msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
  </div>

   <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel-heading">
      <h2>About</h2>
    </div>
    <div class="panel-body">
      <h3>Yasin Erdem</h3>
      <a href="https://github.com/ysnerdem" target="_blank">Github</a>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <div class="form-group">
    <%= f.file_field :image, input_html: { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, input_html: { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_field :content, input_html: { class: "form-control"} %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Post</h1>
      </div>
      <div class="panel-body">
        <strong>Current Image</strong>
        <br>
        <%= image_tag @post.image.url(:medium) %>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div id="posts" class="transitions-enabled">
  <% @posts.each do |post| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag post.image.url), post %>
      <h2><%= link_to post.title, post %></h2>
      <p><%= post.created_at.strftime("%B, %d, %Y") %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Post</h1>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading post_image">
        <%= image_tag @post.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1><%= @post.title %></h1>
        <p class="content"><%= @post.content %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if admin_signed_in? %>
                <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
                <%= link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>